### ISSUE TITLE
size 다른 Image Upload시 나타나는 CUDA Error 처리

### ISSUE THREAD

**Issue by SAgiKPJH** [SagiK-Repository/Docker_AI_Image_RemovePart_Service#11]

**Comment by SAgiKPJH** [comment]
# Log 내용
```log
2024-01-05 16:34:07 [2024-01-05 07:34:07,043][__main__][CRITICAL] - Prediction failed due to CUDA error: unknown error:
2024-01-05 16:34:07 Traceback (most recent call last):
2024-01-05 16:34:07   File "/home/user/lama/bin/predict.py", line 85, in main
2024-01-05 16:34:07     batch = model(batch)
2024-01-05 16:34:07   File "/home/user/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
2024-01-05 16:34:07     result = self.forward(*input, **kwargs)
2024-01-05 16:34:07   File "/home/user/lama/saicinpainting/training/trainers/default.py", line 70, in forward
2024-01-05 16:34:07     batch['predicted_image'] = self.generator(masked_img)
2024-01-05 16:34:07   File "/home/user/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
2024-01-05 16:34:07     result = self.forward(*input, **kwargs)
2024-01-05 16:34:07   File "/home/user/lama/saicinpainting/training/modules/ffc.py", line 367, in forward
2024-01-05 16:34:07     return self.model(input)
2024-01-05 16:34:07   File "/home/user/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
2024-01-05 16:34:07     result = self.forward(*input, **kwargs)
2024-01-05 16:34:07   File "/home/user/miniconda3/lib/python3.9/site-packages/torch/nn/modules/container.py", line 119, in forward
2024-01-05 16:34:07     input = module(input)
2024-01-05 16:34:07   File "/home/user/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
2024-01-05 16:34:07     result = self.forward(*input, **kwargs)
2024-01-05 16:34:07   File "/home/user/lama/saicinpainting/training/modules/ffc.py", line 252, in forward
2024-01-05 16:34:07     x_l, x_g = self.ffc(x)
2024-01-05 16:34:07   File "/home/user/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
2024-01-05 16:34:07     result = self.forward(*input, **kwargs)
2024-01-05 16:34:07   File "/home/user/lama/saicinpainting/training/modules/ffc.py", line 221, in forward
2024-01-05 16:34:07     out_xl = self.convl2l(x_l) + self.convg2l(x_g) * g2l_gate
2024-01-05 16:34:07   File "/home/user/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
2024-01-05 16:34:07     result = self.forward(*input, **kwargs)
2024-01-05 16:34:07   File "/home/user/miniconda3/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 399, in forward
2024-01-05 16:34:07     return self._conv_forward(input, self.weight, self.bias)
2024-01-05 16:34:07   File "/home/user/miniconda3/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 392, in _conv_forward
2024-01-05 16:34:07     return F.conv2d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
2024-01-05 16:34:07 RuntimeError: CUDA error: unknown error
2024-01-05 16:34:07 
2024-01-05 16:34:07 
2024-01-05 16:34:07 172.17.0.1 - - [05/Jan/2024 07:34:07] "POST /running HTTP/1.1" 200 -
```

**Comment by SAgiKPJH** [comment]
# 현재까지 파악된 내용
1. 제공된 이미지로의 LaMa 동작은 문제 없습니다.
2. (추측) 제공된 이미지 Size와 같으면 문제 없습니다.
3. size가 다른 이미지가 들어가면 문제가 발생합니다.

**Comment by SAgiKPJH** [comment]
# 확인 사항

- [x] Size만 같으면 되는가? 그 Size는?
  - 아니다. 
  - 서로 다른 Size인 `1152X768`, `1499X996`도 동작했다.
  - 문제가 된 이미지 Size는 `5872X4032`이다.
  - 이미지가 너무 커서 발생한 문제로 추측
- [ ] ~~LaMa에서 특정 Size만 허용하는가?~~

### 확인 사이트
- sample Image 링크 : https://drive.google.com/drive/folders/1B2x7eQDgecTL0oh3LSIBDGj0fTxs6Ips?usp=drive_link
- git LaMA : https://github.com/advimman/lama

**Comment by SAgiKPJH** [comment]
# 실험 1. 이미지가 너무 크면 안된다?

- `5872X4032` -(1/2)-> `2936X2016`
  - 실패
- `5872X4032` -(1/4)-> `1468X1008`
  - 성공

* 따라서 이미지 크기에 따라 좌우됨을 확인하였습니다.

**Comment by SAgiKPJH** [comment]
# 이미지가 커도 가능하게끔 설정하기

-
